[package]
name = "ics-dm-cli"
version = "0.11.0"
authors = ["Marcel Lilienthal <134974+mlilien@users.noreply.github.com>",
           "Jan Zachmann <jan.zachmann@conplement.de>"]
edition = "2021"
build = "src/build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1"
base64 = "0.13.0"
bollard = "0.11.*"
bzip2 = "0.4.1"
dirs = "4.*"
env_logger = "0.8"
filemagic = "0.12"
flate2 = "1.0.22"
fs_extra = "1.2.0"
futures-executor = "0.3.15"
futures-util = "0.3.15"
hex = "0.4.3"
ics-dm-crypto = { git = "ssh://git@github.com/ICS-DeviceManagement/ics-dm-crypto.git", tag="0.1.0"}
lazy_static = "1.4.0"
log = "0.4"
openssl = { version = "0.10" }
openssl-sys = "0.9"
path-absolutize = "3.0.10"
regex = "1.5.5"
serde = "1.0.*"
serde_json = "1.0.59"
serde_path_to_error = "0.1.*"
stdext = "0.3.*"
structopt = "0.3.21"
tempfile = "3.2.0"
tokio = { version = "1.13.*", features = ["macros", "io-std", "io-util", "fs"] }
toml = "0.5.*"
uuid = { version = "0.8", default-features = false, features = ["v4"] }
validator = { version = "0.14", features = ["derive"] }
xz2 = "0.1"
