[package]
name = "ics-dm-cli"
version = "0.2.1"
authors = ["Marcel Lilienthal <134974+mlilien@users.noreply.github.com>",
           "Jan Zachmann <jan.zachmann@conplement.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
bollard = "0.11.0"
futures-util = "0.3.15"
futures-executor = "0.3.15"
tokio = { version = "1.6.1", features = ["macros"] }
serde_json = "1.0.59"
dirs = "1.0.5"
base64 = "0.13.0"
fs_extra = "1.2.0"
path-absolutize = "3.0.10"
once_cell = "1.8.0"
uuid = { version = "0.8", default-features = false, features = ["v4"] }
tempfile = "3.2.0"
