[package]
name = "omnect-cli"
version = "0.16.3"
authors = ["omnect@conplement.de>"]
edition = "2021"
build = "src/build.rs"
description = "This tools helps to configure your omnect device images."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/omnect/omnect-cli"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13"
actix-web = "4.4"
anyhow = "1"
base64 = "0.13.0"
bollard = { version = "0.13", features = ["ssl"] }
bzip2 = "0.4.1"
clap = { version = "4.0", features = ["derive"] }
directories = "5.0.1"
dirs = "4.*"
env_logger = "0.8"
filemagic = "0.12"
flate2 = "1.0.22"
fs_extra = "1.2.0"
futures = "0.3.28"
futures-executor = "0.3.15"
futures-util = "0.3.15"
hex = "0.4.3"
omnect-crypto = { git = "https://github.com/omnect/omnect-crypto.git", tag = "0.4.0" }
keyring = "2.0.4"
lazy_static = "1.4.0"
log = "0.4"
num_cpus = "1.13"
oauth2 = "4.4.1"
open = "4.1.0"
openssl = { version = "0.10" }
openssl-sys = "0.9"
path-absolutize = "3.0.10"
regex = "1.5.5"
reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.*"
serde_json = "1.0.59"
serde_path_to_error = "0.1.*"
stdext = "0.3.*"
tempfile = "3.2.0"
tokio = { version = "1", features = ["macros", "io-std", "io-util", "fs", "net"] }
toml = "0.5.*"
uuid = { version = "0.8", default-features = false, features = ["v4"] }
url = "2.4.0"
validator = { version = "0.14", features = ["derive"] }
xz2 = "0.1"

[dev-dependencies]
httpmock = "0.6"
file_diff = "1.0"
