hostname= "test"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "my-scope-id"

[provisioning.attestation]
method = "x509"
registration_id = "test"
identity_cert = { method = "est", common_name = "test" }

[cert_issuance.est]
trusted_certs = [
     "file:///mnt/cert/ca/ca.crt",
]

[cert_issuance.est.auth]
identity_cert = "file:///mnt/cert/priv/device_id_cert.pem"
identity_pk = "file:///mnt/cert/priv/device_id_cert_key.pem"            # file URI, or...

[cert_issuance.est.urls]
default = "https://ics-dm-est.url:8080/.well-known/est"

