hostname = "my-ics-iotedge-gateway-device"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "my-scope-id"

[provisioning.attestation]
method = "tpm"
trust_bundle_cert = "file:///var/secrets/trust-bundle.pem"

[edge_ca]
cert = "file:///var/secrets/edge-ca.pem"
pk = "file:///var/secrets/edge-ca.key.pem"
