hostname= "test"

[provisioning]
source = "dps"
global_endpoint = "https://global.azure-devices-provisioning.net"
id_scope = "my-scope-id"
payload = { uri = "file:///etc/omnect/dps-payload.json" }

[provisioning.attestation]
method = "tpm"