
hostname = "my-ics-iot-leaf-device"

local_gateway_hostname = "my-ics-iotedge-gateway-device"

[provisioning]
source = "manual"                                                               # don't change
iothub_hostname = "my-iothub.azure-devices.net"
device_id = "my-device-id"

[provisioning.authentication]
method = "sas"                                                                  # don't change
device_id_pk = { value = "AbCdEfG0123456789=" }                                 # inline key (base64), or...
